"""
Generate Fintra section components for the TBN Next.js app.

Pipeline per chunk:
    body markup -> collapse split-text spans -> replace JS counters with static
    figures -> substitute copy -> rewrite asset and link paths -> JSX -> .tsx
"""
import html as H
import json
import os
import re

from h2jsx import html_to_jsx
import content

ROOT = os.path.abspath("..")
OUT = os.path.join(ROOT, "components", "fintra")
os.makedirs(OUT, exist_ok=True)

b = open("body_flat.html", encoding="utf-8").read()

# ---------------------------------------------------------------- counters --
COUNTER_OPEN = re.compile(r'<div class="framer-\w+-container" data-code-component-plugin-id="84d4c1">')


def match_close(s: str, open_end: int) -> int:
    """Index just past the </div> that closes the div opened before open_end."""
    depth = 1
    for m in re.finditer(r"</?div\b[^>]*?(/?)>", s[open_end:]):
        if m.group(0).startswith("</"):
            depth -= 1
            if depth == 0:
                return open_end + m.end()
        elif not m.group(1):
            depth += 1
    raise ValueError("unbalanced div")


def replace_counters(src: str) -> tuple[str, int]:
    """Swap each JS digit-roller for a plain figure that renders without JS."""
    out, pos, i = [], 0, 0
    while True:
        m = COUNTER_OPEN.search(src, pos)
        if not m:
            out.append(src[pos:]); break
        end = match_close(src, m.end())
        # font styling is inherited from the surrounding Framer text block
        value = content.COUNTERS[i % len(content.COUNTERS)]
        out.append(src[pos:m.start()])
        out.append(
            '<div class="framer-static-counter" '
            'style="display:inline-flex;align-items:center;'
            'font-variant-numeric:tabular-nums">' + value + "</div>"
        )
        pos, i = end, i + 1
    return "".join(out), i


# ------------------------------------------------------------------- copy ---
def substitute(src: str, mapping: dict) -> tuple[str, int]:
    """Replace whole text nodes only, longest key first."""
    n = 0
    keys = sorted(mapping, key=len, reverse=True)

    def repl(m):
        nonlocal n
        raw = m.group(1)
        key = re.sub(r"\s+", " ", H.unescape(raw)).strip()
        if key in mapping:
            n += 1
            lead = raw[: len(raw) - len(raw.lstrip())]
            tail = raw[len(raw.rstrip()):]
            return ">" + lead + H.escape(mapping[key], quote=False) + tail + "<"
        return m.group(0)

    return re.sub(r">([^<>]+)<", repl, src), n


def rewrite_paths(src: str) -> str:
    src = src.replace('src="images/', 'src="/images/')
    src = re.sub(r'srcset="([^"]*)"',
                 lambda m: 'srcset="' + m.group(1).replace("images/", "/images/") + '"', src)
    for a, bb in content.LINKS.items():
        src = src.replace(f'href="{a}"', f'href="{bb}"')
    return src


# --------------------------------------------------------------- sections ---
def find_section(name: str) -> tuple[int, int]:
    m = re.search(r'<(section|div|nav|footer)[^>]*data-framer-name="%s"' % re.escape(name), b)
    if not m:
        raise KeyError(name)
    tag = m.group(1)
    open_end = b.index(">", m.start()) + 1
    depth = 1
    for t in re.finditer(r"</?%s\b[^>]*?(/?)>" % tag, b[open_end:]):
        if t.group(0).startswith("</"):
            depth -= 1
            if depth == 0:
                return m.start(), open_end + t.end()
        elif not t.group(1):
            depth += 1
    raise ValueError(name)


COMPONENT = '''/* eslint-disable @next/next/no-img-element */
/**
 * {title} - ported from the Originkit Fintra export.
 *
 * The DOM is Fintra's, unchanged: the same wrappers, class names and inline
 * styles, because `app/framer.css` is written against this exact structure.
 * Only the copy is Tunga Bhadra Networks'.
 *
 * Generated by _work/build.py - re-run it rather than hand-editing structure.
 */
export default function {comp}() {{
  return (
    <>{jsx}</>
  );
}}
'''


def emit(comp: str, title: str, markup: str, mapping: dict):
    markup, ncount = replace_counters(markup)
    markup, ntext = substitute(markup, mapping)
    markup = rewrite_paths(markup)
    jsx = html_to_jsx(markup)
    path = os.path.join(OUT, f"{comp}.tsx")
    open(path, "w", encoding="utf-8").write(
        COMPONENT.format(title=title, comp=comp, jsx=jsx))
    print(f"  {comp:16} {len(jsx):9,} chars   {ntext:3} strings   {ncount} counters")


if __name__ == "__main__":
    print("generating Fintra section components:\n")

    # nav + footer live outside the main content container
    nav_start = b.index('<div class="framer-1j7zx2v-container"')
    nav_end = match_close(b, b.index(">", nav_start) + 1)
    emit("Nav", "Site navigation", b[nav_start:nav_end], content.NAV)

    foot_start = b.index('<div class="framer-t29m41-container"')
    foot_end = match_close(b, b.index(">", foot_start) + 1)
    emit("SiteFooter", "Site footer", b[foot_start:foot_end], content.FOOTER)

    sections = [
        ("Hero", "Hero", content.HERO),
        ("AboutBand", "About Us", content.BODY),
        ("FeaturesBand", "Features", content.BODY),
        ("WorkflowBand", "Workflow", content.BODY),
        ("MetricsBand", "Metrics", content.BODY),
        ("WhyBand", "Security", content.BODY),
        ("AudienceBand", "Teams", content.BODY),
        ("CompareBand", "Comparison", content.BODY),
        ("TechBand", "Integrations", content.BODY),
        ("VersusBand", "Comparision", content.BODY),
        ("TuitionBand", "Pricing", content.BODY),
        ("FaqBand", "FAQ", content.BODY),
    ]
    for comp, framer_name, mapping in sections:
        s, e = find_section(framer_name)
        emit(comp, framer_name, b[s:e], mapping)


# ---------------------------------------------------------------------------
# Slotted components: same Fintra markup, but with the copy replaced by props
# so every interior page can reuse the section instead of duplicating 12KB.
# ---------------------------------------------------------------------------

SLOTTED = '''/* eslint-disable @next/next/no-img-element */

/**
 * {title} - Fintra's own markup with its copy lifted into props.
 *
 * Structure, class names and inline styles are untouched, so framer.css styles
 * it exactly as it styles the template. Generated by _work/build.py.
 */
export type {comp}Props = {{
{proptypes}
}};

export default function {comp}({{
{propnames}
}}: {comp}Props) {{
  return (
    <>{jsx}</>
  );
}}
'''


def emit_slotted(comp: str, title: str, markup: str, slots: dict, props: dict):
    """`slots` maps a Fintra string to the JSX expression that replaces it."""
    markup, _ = replace_counters(markup)
    markup = rewrite_paths(markup)
    jsx = html_to_jsx(markup)

    for literal, expr in slots.items():
        # text nodes first, then any surviving attribute value (href)
        jsx = jsx.replace(f">{literal}<", f">{expr}<")
        jsx = jsx.replace(f'href="{literal}"', f"href={{{expr.strip('{}')}}}"
                          if expr.startswith("{") else f'href="{literal}"')

    proptypes = "\n".join(f"  {k}: {v};" for k, v in props.items())
    propnames = "\n".join(f"  {k}," for k in props)
    path = os.path.join(OUT, f"{comp}.tsx")
    open(path, "w", encoding="utf-8").write(
        SLOTTED.format(title=title, comp=comp, jsx=jsx,
                       proptypes=proptypes, propnames=propnames))
    print(f"  {comp:16} {len(jsx):9,} chars   {len(props)} props")


def build_slotted():
    print("\ngenerating reusable (slotted) sections:\n")

    s, e = find_section("Hero")
    emit_slotted(
        "PageHero", "Page hero", b[s:e],
        slots={
            "4.9": "{statOneValue}",
            "TrustPilot": "{statOneLabel}",
            "5.0": "{statTwoValue}",
            "Google Business": "{statTwoLabel}",
            "Engineering the future of": "{titleTop}",
            "modern financial systems": "{titleBottom}",
            "Power smarter financial operations with intelligent systems built.": "{subtitle}",
            "Contact Us": "{ctaLabel}",
            "/contact": "{ctaHref}",
        },
        props={
            "titleTop": "string",
            "titleBottom": "string",
            "subtitle": "string",
            "statOneValue": "string",
            "statOneLabel": "string",
            "statTwoValue": "string",
            "statTwoLabel": "string",
            "ctaLabel": "string",
            "ctaHref": "string",
        },
    )


if __name__ == "__main__":
    build_slotted()


CARD_TPL = '''/* eslint-disable @next/next/no-img-element */
import Link from "next/link";

/**
 * Fintra's feature card, lifted out of the Security band.
 *
 * All three of Framer's breakpoint variants are kept: they carry different
 * `framer-v-*` classes that framer.css sizes differently, so dropping any one
 * of them breaks the card at that width. Wrapping it in a link is the only
 * addition - the markup inside is the template's own.
 */
export type FintraCardProps = {
  title: string;
  body: string;
  href?: string;
};

export default function FintraCard({ title, body, href }: FintraCardProps) {
  const card = (
    <>%%JSX%%</>
  );
  return href ? (
    <Link href={href} className="tbn-card-link" aria-label={title}>
      {card}
    </Link>
  ) : (
    card
  );
}
'''


def build_card():
    markup = rewrite_paths(open("card.html", encoding="utf-8").read())
    jsx = html_to_jsx(markup)
    jsx = jsx.replace(">Global Compliance<", ">{title}<")
    jsx = jsx.replace(
        ">Stay compliant with international standards including PCI DSS and SOC frameworks<",
        ">{body}<")
    open(os.path.join(OUT, "FintraCard.tsx"), "w", encoding="utf-8").write(
        CARD_TPL.replace("%%JSX%%", jsx))
    print(f"  {'FintraCard':16} {len(jsx):9,} chars   3 breakpoint variants")


build_card()


SHELL_TPL = '''/* eslint-disable @next/next/no-img-element */
import type { ReactNode } from "react";

/**
 * Fintra's card-band section, with its grid left intact and its contents
 * opened up. Section shell, eyebrow pill and heading are the template's;
 * anything passed as children lands inside Fintra's own card container, so a
 * variable-length list still lays out exactly the way the template does.
 */
export type FintraCardSectionProps = {
  eyebrow: string;
  title: string;
  children: ReactNode;
  id?: string;
};

export default function FintraCardSection({
  eyebrow,
  title,
  children,
  id,
}: FintraCardSectionProps) {
  return (
    <section id={id}>%%JSX%%</section>
  );
}
'''


def build_card_section():
    """Open up the Security band's grid so it can host a variable-length list."""
    start, end = find_section("Security")            # returns outer <section> range
    open_end = b.index(">", start) + 1
    markup = b[open_end:end - len("</section>")]     # inside the section root

    # blank out the card container's contents, keeping the container itself
    cm = re.search(r'<div class="framer-u1hxtd"[^>]*>', markup)
    coe = cm.end()
    depth = 1
    for t in re.finditer(r"</?div\b[^>]*?(/?)>", markup[coe:]):
        if t.group(0).startswith("</"):
            depth -= 1
            if depth == 0:
                cend = coe + t.start()
                break
        elif not t.group(1):
            depth += 1
    markup = markup[:coe] + "@@CHILDREN@@" + markup[cend:]

    jsx = html_to_jsx(rewrite_paths(markup))
    jsx = jsx.replace(">Security<", ">{eyebrow}<")
    jsx = jsx.replace(">Security You Can Trust<", ">{title}<")
    jsx = jsx.replace("@@CHILDREN@@", "{children}")

    open(os.path.join(OUT, "FintraCardSection.tsx"), "w", encoding="utf-8").write(
        SHELL_TPL.replace("%%JSX%%", jsx))
    print(f"  {'FintraCardSection':16} {len(jsx):9,} chars   grid opened for children")


build_card_section()
