"""
Split Fintra's page into the three fragments a multi-page site needs.

The export is a single-page document: its nav and footer live inside the same
`#main` blob as the homepage sections. Rendering that blob as the homepage gave
the homepage real chrome and left every other route with none - no nav, no
footer, no stylesheet scope.

So the page is cut at its own seams:

    #main
      div.framer-8VCee.framer-12flmqb        <- page shell  (layout)
        div.framer-1j7zx2v-container         <- NAV         (layout)
        div[data-framer-root].framer-9LKbR   <- content root(layout)
          ...sections                        <- PAGE BODY   (per route)
        div.framer-t29m41-container          <- FOOTER      (layout)

Nav, footer and both wrapper tags go in the root layout; each route supplies
only its sections. The wrapper classes matter: `framer-Efl2Y` and its siblings
are the scopes the typography presets are written against, so the chain has to
be reproduced exactly or every heading loses its styling.
"""
import json
import os
import re

import content
import reveal
import splittext
from exact import main_inner, main_tag_attrs, rewrite_paths, substitute

ROOT = os.path.abspath("..")
OUT = os.path.join(ROOT, "components", "fintra", "html")
os.makedirs(OUT, exist_ok=True)

NAV_CLASS = "framer-1j7zx2v-container"
FOOTER_CLASS = "framer-t29m41-container"


def block(doc: str, cls: str) -> tuple[int, int]:
    """Byte range of the whole <div class="cls" ...>...</div>."""
    m = re.search(r'<div class="%s"[^>]*>' % re.escape(cls), doc)
    if not m:
        raise KeyError(cls)
    open_end = m.end()
    depth = 1
    for t in re.finditer(r"</?div\b[^>]*?(/?)>", doc[open_end:]):
        if t.group(0).startswith("</"):
            depth -= 1
            if depth == 0:
                return m.start(), open_end + t.end()
        elif not t.group(1):
            depth += 1
    raise ValueError(cls)


def content_root(doc: str) -> tuple[dict, int, int]:
    """Attributes of the [data-framer-root] wrapper, and the range of its children."""
    m = re.search(r"<div data-framer-root([^>]*)>", doc)
    attrs = {}
    for a in re.finditer(r"""([\w-]+)(?:=(?:"([^"]*)"|'([^']*)'))?""", m.group(1)):
        name = a.group(1)
        attrs[name] = a.group(2) if a.group(2) is not None else (a.group(3) or "")
    open_end = m.end()
    depth = 1
    for t in re.finditer(r"</?div\b[^>]*?(/?)>", doc[open_end:]):
        if t.group(0).startswith("</"):
            depth -= 1
            if depth == 0:
                return attrs, open_end, open_end + t.start()
        elif not t.group(1):
            depth += 1
    raise ValueError("content root")


TS_HTML = """/* eslint-disable */
/**
 * %s
 *
 * Fintra's markup exactly as the Originkit export ships it - every wrapper,
 * class and inline style preserved, because framer.css is written against this
 * DOM. Only the copy is Tungabadra Networks'.
 *
 * Generated by _work/fragments.py. Do not hand-edit.
 */
const html = %s;

export default html;
"""

TS_OBJ = """/* eslint-disable */
/**
 * %s
 *
 * Generated by _work/fragments.py. Do not hand-edit.
 */
const attrs: Record<string, string> = %s;

export default attrs;
"""

TS_ROOT = """/* eslint-disable */
/**
 * Fintra's [data-framer-root] wrapper.
 *
 * The class list carries the typography-preset scopes - `framer-Efl2Y` and its
 * siblings are what the `.framer-Efl2Y .framer-styles-preset-*` rules hang off
 * - so it has to be reproduced exactly or every heading loses its styling.
 *
 * `display: contents` keeps the page sections laid out by the shell above
 * rather than by this wrapper, which is how the export centres them.
 *
 * Generated by _work/fragments.py. Do not hand-edit.
 */
import type { CSSProperties } from "react";

export const rootClassName = %s;

export const rootStyle: CSSProperties = %s;
"""


def emit_root(attrs: dict):
    style = {}
    for decl in attrs.get("style", "").split(";"):
        if ":" not in decl:
            continue
        k, _, v = decl.partition(":")
        k = k.strip()
        key = k if k.startswith("--") else re.sub(r"-(\w)", lambda m: m.group(1).upper(), k)
        style[key] = v.strip()
    open(os.path.join(OUT, "rootAttrs.ts"), "w", encoding="utf-8").write(
        TS_ROOT % (json.dumps(attrs.get("class", "")), json.dumps(style, indent=1)))
    print("  %-16s className + %d style declarations" % ("rootAttrs", len(style)))


def emit_html(name: str, label: str, markup: str):
    open(os.path.join(OUT, name + ".ts"), "w", encoding="utf-8").write(
        TS_HTML % (label, json.dumps(markup)))
    print("  %-16s %9s chars" % (name, format(len(markup), ",")))


def emit_attrs(name: str, label: str, attrs: dict):
    open(os.path.join(OUT, name + ".ts"), "w", encoding="utf-8").write(
        TS_OBJ % (label, json.dumps(attrs, indent=1)))
    print("  %-16s %d attributes" % (name, len(attrs)))


def prepare(doc: str) -> str:
    """Copy swap + reveal handling, in the order the other generators use."""
    doc, report = splittext.replace_all(doc, content.SPLIT)
    for k, v in report.items():
        print("     split-text [%s] %s" % (v, k[:44]))
    from exact import substitute_by_region
    doc, n = substitute_by_region(doc)
    print("  text nodes replaced: %d" % n)
    doc, freed, kept = reveal.free_hidden(doc)
    doc, risen = reveal.free_rise(doc)
    print("  hidden states freed: %d | left to Framer's animator: %d" % (freed, kept))
    print("  frozen scroll offsets freed: %d" % risen)
    return rewrite_paths(doc)


if __name__ == "__main__":
    raw = open(os.path.join(ROOT, "fintra", "index.html"), encoding="utf-8").read()
    body = prepare(main_inner(raw))
    print()

    ns, ne = block(body, NAV_CLASS)
    fs, fe = block(body, FOOTER_CLASS)
    root_attrs, cs, ce = content_root(body)

    emit_html("nav", "Site navigation, shared by every route", body[ns:ne])
    emit_html("footer", "Site footer, shared by every route", body[fs:fe])
    emit_html("home", "Home page sections", body[cs:ce])

    # The homepage hero is now the Originkit "Hero 18" section, so emit the
    # body a second time without Fintra's own hero. The other eleven sections
    # are untouched, and interior routes still use Fintra's hero.
    inner = body[cs:ce]
    hm = re.search(r'<section class="framer-rwk6nd"[^>]*>', inner)
    depth, hero_end = 1, None
    for t in re.finditer(r"</?section\b[^>]*?(/?)>", inner[hm.end():]):
        if t.group(0).startswith("</"):
            depth -= 1
            if depth == 0:
                hero_end = hm.end() + t.end()
                break
        elif not t.group(1):
            depth += 1
    emit_html("homeNoHero", "Home page sections, minus Fintra's hero",
              inner[:hm.start()] + inner[hero_end:])
    emit_attrs("mainAttrs", "The #main attributes from the Fintra export",
               main_tag_attrs(raw))
    emit_root(root_attrs)
