"""
Turn Fintra's hero into a fill-in template shared by every route.

Thirteen of eighteen pages were using a hand-built header instead of the
template's, which is what made the site read as several different designs. The
hero markup is identical on every page, so it becomes one template with typed
slots and the pages differ only by copy.

Placeholders appear once per breakpoint variant (Framer emits three), so the
component fills them with replaceAll rather than replace.
"""
import json
import os
import re

import content
import reveal
import splittext
from exact import main_inner, rewrite_paths, substitute_by_region

ROOT = os.path.abspath("..")
OUT = os.path.join(ROOT, "components", "fintra", "html")


def hero_markup() -> str:
    raw = open(os.path.join(ROOT, "fintra", "index.html"), encoding="utf-8").read()
    body = main_inner(raw)
    body, _ = splittext.replace_all(body, content.SPLIT)
    body, _ = substitute_by_region(body)
    body, _, _ = reveal.free_hidden(body)
    body = rewrite_paths(body)

    m = re.search(r'<section class="framer-rwk6nd"[^>]*>', body)
    open_end, depth = m.end(), 1
    for t in re.finditer(r"</?section\b[^>]*?(/?)>", body[open_end:]):
        if t.group(0).startswith("</"):
            depth -= 1
            if depth == 0:
                return body[m.start():open_end + t.end()]
        elif not t.group(1):
            depth += 1
    raise ValueError("hero")


# The title is a run of per-word spans; collapse each run to one placeholder.
# reveal.py adds data-tbn-reveal to each word span, so allow trailing attributes.
WORD_RUN = re.compile(
    r'<span style="[^"]*"[^>]*>[A-Za-z][^<>]*</span>'
    r'(?:\s*<span style="[^"]*"[^>]*>[^<>]*</span>)+')


def templatize(hero: str) -> tuple[str, dict]:
    counts = {}

    def bump(k):
        counts[k] = counts.get(k, 0) + 1

    # 1. title: whole word-span run -> {{TITLE}}
    def title_sub(m):
        bump("TITLE")
        return "{{TITLE}}"
    hero = WORD_RUN.sub(title_sub, hero)

    # 2. remaining single text nodes
    # These must track content.py's HERO map - the hero markup carries whatever
    # copy that produced, and the slots are cut out of it.
    plain = {
        "Industry-focused networking training, real enterprise labs, and placement support.": "SUBTITLE",
        "Book a Demo": "CTA",
        "Trained": "S1L",
        "Placed": "S2L",
    }

    def node_sub(m):
        raw = m.group(1)
        key = re.sub(r"\s+", " ", raw).strip()
        if key in plain:
            bump(plain[key])
            return ">{{%s}}<" % plain[key]
        if key == "3,000+":
            bump("S1V"); return ">{{S1V}}<"
        if key == "950+":
            bump("S2V"); return ">{{S2V}}<"
        return m.group(0)

    hero = re.sub(r">([^<>]{1,140})<", node_sub, hero)

    # 3. the button target
    hero, n = re.subn(r'href="[^"]*"', 'href="{{HREF}}"', hero)
    counts["HREF"] = n
    return hero, counts


TS = '''/* eslint-disable */
/**
 * Fintra's hero, as a fill-in template.
 *
 * Exactly the export's markup - all three breakpoint variants, every wrapper
 * and inline style - with the copy replaced by slots. Every route renders this
 * so the site has one hero instead of the four different headers it grew.
 *
 * Each placeholder occurs once per breakpoint variant, so fill with replaceAll.
 *
 * Generated by _work/herotpl.py. Do not hand-edit.
 */
const heroTemplate = %s;

export default heroTemplate;
'''

if __name__ == "__main__":
    hero = hero_markup()
    tpl, counts = templatize(hero)
    open(os.path.join(OUT, "heroTemplate.ts"), "w", encoding="utf-8").write(
        TS % json.dumps(tpl))
    print("hero template: %s chars" % format(len(tpl), ","))
    for k, v in sorted(counts.items()):
        print("   {{%s}} x%d" % (k, v))
    left = sorted({re.sub(r"\s+", " ", m.group(1)).strip()
                   for m in re.finditer(r">([^<>]{2,120})<", tpl)
                   if not m.group(1).strip().startswith("{{")})
    print("   unslotted text remaining:", left)
